# Generated by Django 4.0.6 on 2022-08-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_certificate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ver_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
