# Generated by Django 4.0.6 on 2022-08-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate_ver_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='ver_link',
            new_name='verification_link',
        ),
    ]
