# Generated by Django 4.0.6 on 2022-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_certificate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
