# Generated by Django 4.0.6 on 2022-08-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_certificate_course_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
