# Generated by Django 4.0.6 on 2022-08-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='is_key_skill',
            new_name='is_coding_skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='is_framework',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_key_interest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_webtech',
            field=models.BooleanField(default=True),
        ),
    ]
