# Generated by Django 4.0.6 on 2022-08-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_is_key_skill_skill_is_coding_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
