# Generated by Django 4.0.6 on 2022-08-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='date',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
