# Generated by Django 4.0.6 on 2022-08-26 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userprofile_experiences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='experiences',
        ),
    ]
