# Generated by Django 4.0.6 on 2022-08-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_experience_from_date_alter_experience_to_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
