# Generated by Django 4.0.6 on 2022-08-26 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
