# Generated by Django 4.0.6 on 2022-08-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactprofile',
            name='subject',
            field=models.CharField(default='Hello', max_length=300, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
