# Generated by Django 4.0.6 on 2022-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_contactprofile_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='to_display',
            field=models.BooleanField(default=True),
        ),
    ]
