# Generated by Django 4.0.6 on 2022-08-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_blog_to_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='git_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='show_git',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='doi_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='research_gate_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
