# Generated by Django 4.0.6 on 2022-08-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_portfolio_git_link_portfolio_show_git_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
