# Generated by Django 4.0.6 on 2022-08-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_portfolio_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
    ]
