# Generated by Django 4.0.6 on 2022-08-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_portfolio_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['priority'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio Profiles'},
        ),
    ]
