# Generated by Django 4.0.6 on 2022-08-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_portfolio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactprofile',
            options={'ordering': None, 'verbose_name': 'Contact Profile', 'verbose_name_plural': 'Contact Profiles'},
        ),
    ]
