# Generated by Django 4.0.6 on 2022-08-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_quote_testimonial_major_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': None, 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
