# Generated by Django 4.0.6 on 2022-08-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_testimonial_options_testimonial_cgpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['id'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
