# Generated by Django 4.0.6 on 2022-09-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_blog_image_filename_portfolio_image_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
