# Generated by Django 4.0.6 on 2022-09-02 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_blog_slug_alter_portfolio_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': None, 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
    ]
